# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d9c66b7121ab86e64787ae9bbcc395ddffa2a3131714c90105228c33988f2eb520c2c9a475f1ba31d201ac6895faa2fa5433bd32f454eb643df0ea859a66a02

test:
  secret_key_base: e9f955c3838326786d0a98088155dcd0077b5eb65b857ecd111adba90558dd4a9ca3c6aa669aabaa9c7979c4b266b5e344b3dfae432868a975c21edd9cddd6b6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
